---
- hosts: localhost
  tasks:
    - name: Check if inventory is empty.
      fail:
        msg: '[ERROR] Empty inventory. No host available.'
      when: groups.all|length == 0

- hosts: web
  remote_user: admin

  pre_tasks:
    - name: Update apt cache if needed.
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - admin
    - role: traefik
    - role: api
      vars:
        docker_image: '{{ docker_image }}'
        env_file: '{{ env_file }}'
        api_domain: '{{ api_domain }}'
