export const QUERY_KEYS = {
  login: 'userLogin',
  register: 'userRegister',
  interests: 'interests',
  userSelectedInterests: 'userSelectedInterests',
  shopItems: 'shopItems',
  userTransactions: 'userTransactions',
  userPoints: 'userPoints',
  events: 'events',
  applyFlyTalk: 'applyFlyTalk',
  currentUser: 'currentUser',
  reward: 'reward',
  achievements: 'achievements',
  achievementCompleted: 'achievementGetCompleted',
  codes: 'codes',
  codeApplied: 'codeApplied',
};
