export const QUERY_KEYS = {
  login: 'userLogin',
  register: 'userRegister',
  interests: 'interests',
  userSelectedInterests: 'userSelectedInterests',
  shopItems: 'shopItems',
  userTransactions: 'userTransactions',
  userPoints: 'userPoints',
  events: 'events',
  eventsMySchedule: 'eventsMySchedule',
  applyFlyTalk: 'applyFlyTalk',
  flyTalkGroups: 'flyTalkGroups',
  currentUser: 'currentUser',
  leaderboard: 'leaderboard',
  leaderboardTop: 'leaderboard-top',
  leaderboardUserRank: 'leaderboard-user-rank',
  reward: 'reward',
  achievements: 'achievements',
  achievementCompleted: 'achievementGetCompleted',
  codes: 'codes',
  codeApplied: 'codeApplied',
  eventParticipantsCount: 'eventParticipantsCount',
  companies: 'companies',
};
