version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: ddays-app
      POSTGRES_USER: dumpovac
      POSTGRES_PASSWORD: dump1234
    ports:
      - 3001:5432
