export enum Path {
  Home = '/admin-old',
  Company = '/admin-old/company',
  Interest = '/admin-old/interest',
  CatchAll = '/admin-old/:path*',
  Event = '/admin-old/event',
  Speaker = '/admin-old/speaker',
  Booth = '/admin-old/booth',
  Reward = '/admin-old/reward',
  Achievement = '/admin-old/achievement',
  Code = '/admin-old/code',
  Accreditation = '/admin-old/accreditation',
  AccreditationScan = '/admin-old/accreditation-scan',
  TransactionScan = '/admin-old/transaction-scan',
  Shopping = '/admin-old/shopping',
}
