export const RouteNames = {
  BASENAME: '/admin',
  HOME: '/',
  ERROR: '*',
  ADMINISTRATORS: '/administrators',
  DATABASE: '/database',
  USERS: '/database/users',
  COMPANIES: '/database/companies',
  SPEAKERS: '/database/speakers',
  INTERESTS: '/database/interests',
  EVENTS: '/database/events',
  BOOTHS: '/database/booths',
  REWARDS: '/database/rewards',
  ACHIEVEMENTS: '/database/achievements',
  CODES: '/database/codes',
  SHOPPING: '/database/shopping',
  FAQS: '/database/faqs',
  MANAGEMENT: '/management',
  ACCREDITATION_PRINT: '/management/accreditation-print',
  ACCREDITATION_SCAN: '/management/accreditation-scan',
  TRANSACTION_SCAN: '/management/transaction-scan',
  SPONSOR_MANAGEMENT: '/sponsor-management',
  POTENTIAL_SPONSORS: '/sponsor-management/potential-sponsors',
  SPONSOR_MATERIALS: '/sponsor-management/sponsor-materials',
  SPONSOR_CONTRACTS: '/sponsor-management/sponsor-contracts',
};
