import { AchievementDto } from '@ddays-app/types';

export type Achievement = AchievementDto & { goal: number; progress: number };

const achievements: Achievement[] = [
  {
    id: 1,
    name: 'First achievement',
    description: 'This is the first achievement',
    points: 20,
    createdAt: new Date(),
    goal: 5,
    progress: 5,
  },
  {
    id: 2,
    name: 'Second achievement',
    description: 'This is the second achievement',
    points: 20,
    createdAt: new Date(),
    goal: 5,
    progress: 3,
  },
  {
    id: 3,
    name: 'Third achievement',
    description: 'This is the third achievement',
    points: 30,
    createdAt: new Date(),
    goal: 5,
    progress: 1,
  },
  {
    id: 4,
    name: 'Fourth achievement',
    description: 'This is the fourth achievement',
    points: 40,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 5,
    name: 'Fifth achievement',
    description: 'This is the fifth achievement',
    points: 50,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 6,
    name: 'Sixth achievement',
    description: 'This is the sixth achievement',
    points: 60,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 7,
    name: 'Seventh achievement',
    description: 'This is the seventh achievement',
    points: 70,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 8,
    name: 'Eighth achievement',
    description: 'This is the eighth achievement',
    points: 80,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 9,
    name: 'Ninth achievement',
    description: 'This is the ninth achievement',
    points: 90,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 10,
    name: 'Tenth achievement',
    description: 'This is the tenth achievement',
    points: 100,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 11,
    name: 'Eleventh achievement',
    description: 'This is the eleventh achievement',
    points: 210,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
  {
    id: 12,
    name: 'Twelfth achievement',
    description: 'This is the twelfth achievement',
    points: 20000,
    createdAt: new Date(),
    goal: 5,
    progress: 0,
  },
];

export default achievements;
