import { CompanyDto } from '@ddays-app/types';

export const companies: CompanyDto[] = [
  {
    id: 1,
    category: 'gold',
    name: 'Tech Innovators Inc.',
    username: 'tech_innovators',
    password: 'securepassword123',
    description: 'Leading the way in cutting-edge technology solutions.',
    opportunitiesDescription:
      'Exciting roles in AI, blockchain, and cloud computing.',
    website: 'https://techinnovators.com',
    instagram: 'https://instagram.com/tech_innovators',
    linkedin: 'https://linkedin.com/company/tech-innovators',
    boothId: 101,
    logoImage: 'https://example.com/logo-tech-innovators.png',
    landingImage: 'https://example.com/landing-tech-innovators.png',
    video: 'https://example.com/video-tech-innovators.mp4',
    codeId: 2001,
    interests: [
      { id: 1, name: 'Artificial Intelligence', theme: 'tech' },
      { id: 2, name: 'Cloud Computing', theme: 'dev' },
    ],
  },
  {
    id: 2,
    category: 'silver',
    name: 'Creative Designs Ltd.',
    username: 'creative_designs',
    password: 'designpass456',
    description: 'Innovative design solutions for modern businesses.',
    opportunitiesDescription:
      'Openings for UX/UI designers and graphic artists.',
    website: 'https://creativedesigns.com',
    instagram: 'https://instagram.com/creative_designs',
    linkedin: 'https://linkedin.com/company/creative-designs',
    boothId: 102,
    logoImage: 'https://example.com/logo-creative-designs.png',
    landingImage: 'https://example.com/landing-creative-designs.png',
    video: 'https://example.com/video-creative-designs.mp4',
    codeId: 2002,
    interests: [
      { id: 3, name: 'User Experience', theme: 'design' },
      { id: 4, name: 'Graphic Design', theme: 'design' },
    ],
  },
  {
    id: 3,
    category: 'bronze',
    name: 'Marketing Gurus Co.',
    username: 'marketing_gurus',
    password: 'marketpass789',
    description: 'Experts in digital marketing and brand strategy.',
    opportunitiesDescription:
      'Join us as a digital marketer or SEO specialist.',
    website: 'https://marketinggurus.com',
    instagram: 'https://instagram.com/marketing_gurus',
    linkedin: 'https://linkedin.com/company/marketing-gurus',
    boothId: 103,
    logoImage: 'https://example.com/logo-marketing-gurus.png',
    landingImage: 'https://example.com/landing-marketing-gurus.png',
    video: 'https://example.com/video-marketing-gurus.mp4',
    codeId: 2003,
    interests: [
      { id: 5, name: 'Digital Marketing', theme: 'marketing' },
      { id: 6, name: 'SEO Optimization', theme: 'tech' },
    ],
  },
  {
    id: 4,
    category: 'media',
    name: 'Media Masters LLC',
    username: 'media_masters',
    password: 'mediapass101',
    description: 'Pioneers in content creation and media solutions.',
    opportunitiesDescription:
      'Positions available for video editors and content writers.',
    website: 'https://mediamasters.com',
    instagram: 'https://instagram.com/media_masters',
    linkedin: 'https://linkedin.com/company/media-masters',
    boothId: 104,
    logoImage: 'https://example.com/logo-media-masters.png',
    landingImage: 'https://example.com/landing-media-masters.png',
    video: 'https://example.com/video-media-masters.mp4',
    codeId: 2004,
    interests: [
      { id: 7, name: 'Content Creation', theme: 'marketing' },
      { id: 8, name: 'Video Production', theme: 'design' },
    ],
  },
  {
    id: 5,
    category: 'friend',
    name: 'Community Partners',
    username: 'community_partners',
    password: 'community123',
    description: 'Supporting community-driven projects and events.',
    opportunitiesDescription:
      'Looking for volunteers and community organizers.',
    website: 'https://communitypartners.com',
    instagram: 'https://instagram.com/community_partners',
    linkedin: 'https://linkedin.com/company/community-partners',
    boothId: 105,
    logoImage: 'https://example.com/logo-community-partners.png',
    landingImage: 'https://example.com/landing-community-partners.png',
    video: 'https://example.com/video-community-partners.mp4',
    codeId: 2005,
    interests: [
      { id: 9, name: 'Community Development', theme: 'dev' },
      { id: 10, name: 'Event Organization', theme: 'marketing' },
    ],
  },
];
