name: Docker image build

on:
  push:
    # todo: uncomment when deployment is done, this is just dummy build
    # branches-ignore:
    #   - main
  workflow_dispatch:

jobs:
  docker_image_build:
    name: Docker image build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build frontend web apps
        run: yarn turbo run build --filter=admin... --filter=sponsor...

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }},
            ghcr.io/${{ github.repository }}:${{ github.ref_name == 'main' && 'latest' || 'unstable' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
