name: Generate migrations

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/db/schema.ts'

jobs:
  generate_migrations:
    name: Generate migrations
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate migrations
        run: yarn generate

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          GIT_BRANCH="migrations-$(date +%s)"
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          git checkout -b $GIT_BRANCH

          git add -f apps/api/db/migrations
          git commit -m "Generate migrations"
          git push origin $GIT_BRANCH

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: process.env.GIT_BRANCH,
              base: 'main',
              title: 'Generate migrations',
            })
