name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  eslint_web:
    name: Run ESLint (web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace web run lint

  eslint_sponsor:
    name: Run ESLint (sponsor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace sponsor run lint

  eslint_admin:
    name: Run ESLint (admin)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace admin run lint

  eslint_api:
    name: Run ESLint (api)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace api run lint

  eslint_app:
    name: Run ESLint (app)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace app run lint
